In [9]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
import pandas as pd

In [50]:
data = [
    ['Skirt', 'Sneakers', 'Scarf', 'Pants', 'Hat'],
    ['Sunglasses', 'Skirt', 'Sneakers', 'Pants', 'Hat'],
    ['Dress', 'Sandals', 'Scarf', 'Pants', 'Heels'],
    ['Dress', 'Necklace', 'Earrings', 'Scarf', 'Hat', 'Heels', 'Hat'],
    ['Earrings', 'Skirt', 'Skirt', 'Scarf', 'Shirt', 'Pants']
]

In [52]:
te = TransactionEncoder()
te_trans = te.fit(data).transform(data)
df = pd.DataFrame(te_trans, columns=te.columns_)

In [53]:
# Apply the apriori algorithm
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

In [54]:
#association rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

In [55]:
print(rules)

           antecedents                           consequents  \
0              (Dress)                               (Heels)
1              (Heels)                               (Dress)
2           (Necklace)                               (Dress)
3            (Sandals)                               (Dress)
4              (Dress)                               (Scarf)
..                 ...                                   ...
670  (Necklace, Dress)         (Heels, Hat, Scarf, Earrings)
671  (Necklace, Heels)         (Hat, Dress, Scarf, Earrings)
672  (Earrings, Dress)         (Hat, Necklace, Scarf, Heels)
673  (Earrings, Heels)         (Dress, Hat, Necklace, Scarf)
674         (Necklace)  (Earrings, Scarf, Hat, Dress, Heels)

     antecedent support  consequent support  support  confidence  lift  \
0                   0.4                 0.4      0.4         1.0  2.50
1                   0.4                 0.4      0.4         1.0  2.50
2                   0.2                 0.4      0.2         1.0  2.50
3                   0.2                 0.4      0.2         1.0  2.50
4                   0.4                 0.8      0.4         1.0  1.25
..                  ...                 ...      ...         ...   ...
670                 0.2                 0.2      0.2         1.0  5.00
671                 0.2                 0.2      0.2         1.0  5.00
672                 0.2                 0.2      0.2         1.0  5.00
673                 0.2                 0.2      0.2         1.0  5.00
674                 0.2                 0.2      0.2         1.0  5.00

     leverage  conviction  zhangs_metric
0        0.24         inf       1.000000
1        0.24         inf       1.000000
2        0.12         inf       0.750000
3        0.12         inf       0.750000
4        0.08         inf       0.333333
..        ...         ...            ...
670      0.16         inf       1.000000
671      0.16         inf       1.000000
672      0.16         inf       1.000000
673      0.16         inf       1.000000
674      0.16         inf       1.000000

[675 rows x 10 columns]

In [56]:
dataset = pd.read_csv('Market_Basket_Optimisation.csv')

In [57]:
dataset.fillna(0, inplace=True)

In [58]:
dataset.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
1,chutney,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
2,turkey,avocado,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
3,mineral water,milk,energy bar,whole wheat rice,green tea,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
4,low fat yogurt,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0

In [66]:
dataset.isnull().sum()

shrimp               0
almonds              0
avocado              0
vegetables mix       0
green grapes         0
whole weat flour     0
yams                 0
cottage cheese       0
energy drink         0
tomato juice         0
low fat yogurt       0
green tea            0
honey                0
salad                0
mineral water        0
salmon               0
antioxydant juice    0
frozen smoothie      0
spinach              0
olive oil            0
dtype: int64

In [62]:
transactions = []
for i in range(len(dataset)):
    transactions.append([str(item) for item in dataset.iloc[i, :].dropna()])

In [63]:
# Convert the dataset to a one-hot encoded format
te = TransactionEncoder()
te_ary = te.fit_transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [64]:
# Apply the apriori algorithm 
frequent_itemsets = apriori(df, min_support=0.02, use_colnames=True)

In [65]:
# Association rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)
print(rules)

                     antecedents          consequents  antecedent support  \
0                            (0)                (0.0)            0.999733
1                          (0.0)                  (0)            1.000000
2                      (almonds)                  (0)            0.020267
3                      (avocado)                  (0)            0.033200
4                     (brownies)                  (0)            0.033733
...                          ...                  ...                 ...
1026  (0.0, tomatoes, spaghetti)                  (0)            0.020933
1027               (0, tomatoes)     (0.0, spaghetti)            0.068400
1028       (tomatoes, spaghetti)             (0, 0.0)            0.020933
1029             (tomatoes, 0.0)       (0, spaghetti)            0.068400
1030                  (tomatoes)  (0, 0.0, spaghetti)            0.068400

      consequent support   support  confidence      lift  leverage  \
0               1.000000  0.999733    1.000000  1.000000  0.000000
1               0.999733  0.999733    0.999733  1.000000  0.000000
2               0.999733  0.020133    0.993421  0.993686 -0.000128
3               0.999733  0.033067    0.995984  0.996250 -0.000124
4               0.999733  0.033733    1.000000  1.000267  0.000009
...                  ...       ...         ...       ...       ...
1026            0.999733  0.020933    1.000000  1.000267  0.000006
1027            0.174133  0.020933    0.306043  1.757520  0.009023
1028            0.999733  0.020933    1.000000  1.000267  0.000006
1029            0.174000  0.020933    0.306043  1.758867  0.009032
1030            0.174000  0.020933    0.306043  1.758867  0.009032

      conviction  zhangs_metric
0            inf       0.000000
1       1.000000       0.000000
2       0.040533      -0.006444
3       0.066400      -0.003879
4            inf       0.000276
...          ...            ...
1026         inf       0.000272
1027    1.190083       0.462663
1028         inf       0.000272
1029    1.190275       0.463130
1030    1.190275       0.463130

[1031 rows x 10 columns]